// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdowoxiwmdlljuivtgbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb3dveGl3bWRsbGp1aXZ0Z2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNzAwMDgsImV4cCI6MjA4ODc0NjAwOH0.WECczsLbHQbGJYn2ga1fSUPf9WQ196DgsEXfR6laQBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});